### ISSUE TITLE
Does it all happen in the browser or is it a client-server solution?

### ISSUE THREAD

**Issue by Mithgol** [binarykitchen/videomail-client#16]
The file `README.md` [currently](https://github.com/binarykitchen/videomail-client/blob/0012360059fa8ad2346d6b6ecf623667c7a91fc4/README.md) says the following:

> Finally you can encode any webcam recordings from your browser into MP4 and WebM within seconds. This without the need for Flash, Java nor any other plugins / addons. Just JavaScript.

Do these resulting MP4 or WebM recordings appear in the browser? (Or are they assembled on some remote server from individual frames?)

I am asking this because I have seen you (@binarykitchen) opening issues such as kripken/emscripten#995 and kripken/emscripten#1042 and bgrins/videoconverter.js#1 and gists such as https://gist.github.com/binarykitchen/5329825 and thus it is very interesting whether your quest for JavaScript version of avconv was eventually successful and whether videomail-client is some result on that path.

The `README.md` says “from your browser” and “within seconds” but it does not say “to a remote server” or “to a buffer in the browser's memory” or anything of that kind.

**Comment by binarykitchen** [comment]
good questions - i managed to port avconv to JS with emscripten, but the JS file became too large, over 100MB. that's a no go.

the current videomail-client version sends frames at high speed to the server, which encodes them all asap and sends back the video. everything is streamed, piped together. it is true what i wrote: all happens within seconds. if your recording is below 2 mins, you won't experience any delays when on a fast connection. so yes, it is a client-server solution for now which works pretty well. lots of deaf people send through emails in sign language.

but soon i want to check out Janus in a separate branch, see https://github.com/binarykitchen/videomail-client/issues/6

**Comment by Mithgol** [comment]
Porting avconv to JavaScript is an outstanding achievement nevertheless. 100MB size may be a “no go” sign for the traditional browser-based applications (where the resource has to be downloaded), but it still might be very useful in Cordova-based mobile applications (where any JavaScript resource resides in the same .apk file and thus it is immediately available). Would you share (in a gist, perhaps; or as a repo because isaacs/github#21 prevents feedback in gists) the steps of your porting? I'd like to give it a try.

**Comment by binarykitchen** [comment]
indeed, it was crazy.

i am afraid, i do not have the files anymore and they all are very unstable (compiled them all with plenty of warnings and without libvpx support). wouldn't recommend these for cordova-based apps anyway.

but if you want to give it a try yourself, these two gists of mine might help a bit:
https://gist.github.com/binarykitchen/5230096
https://gist.github.com/binarykitchen/5329825
