### ISSUE TITLE
Question: Can I submit to other locations

### ISSUE THREAD

**Issue by goodwid** [binarykitchen/videomail-client#179]
I'd like to use your package to submit videos to cloudinary.  Is this workable out of the box, or will I need to edit the code to make this happen?

**Comment by binarykitchen** [comment]
Good question. Not configurable out of the box but with some custom code should be possible. Here an idea (pseudo code):

1. Load videomail-client on your UI
2. Record video upon press of a button
3. Submit to videomail server for encoding
4. Wait for response. It contains links to encoded videos.
5. Fetch these with a GET request and upload these cloudinary

Code for the above should be small and easy I think.

**Comment by goodwid** [comment]
Thanks, but I need a solution that doesn't involve a 3d party server.  Hopefully as a React component, as well.  I dig this project, but it isn't gonna work for my needs as is.  Good stuff, tho. :)

**Comment by binarykitchen** [comment]
Alright, good luck then ;) ...  I doubt there is a client-side-only solution out there.
