### ISSUE TITLE
TypeError: "exports" is read-only

### ISSUE THREAD

**Issue by IanPhilips** [binarykitchen/videomail-client#180]
Hi, love the plugin. I keep getting this error from webpack in my react-gatsby project. Any idea how I can fix it? 
neither of these import methods work:
`let VideomailClient = require('videomail-client');`
`import VideomailClient from 'videomail-client';`

error:
```
TypeError: "exports" is read-only
./node_modules/videomail-client/src/js/util/browser.js/<
node_modules/videomail-client/src/js/util/browser.js:352


  349 | export default Browser
  350 | 
  351 | // so that we also can require() it from videomailError.js within
> 352 | module.exports = Browser
  353 | 

./node_modules/videomail-client/src/js/util/browser.js
http://localhost:8000/commons.js:82452:30

__webpack_require__
/Users/ianphilips/Documents/bizcoreo/webpack/bootstrap:789
```

**Comment by binarykitchen** [comment]
That's a stupid code line of me. 

Removed and fixed:
https://github.com/binarykitchen/videomail-client/commit/9630dab095212eb99d40f433fe19fbfef13531ac#diff-ea3f5006e5dbe3bed262fbb1df32406b19cf775152fddbe6b9123c8a8ecc6c18L352

New patch is out. Thanks for reporting. Go update now.

PS: let me know how it goes integrating into React! Never tried that before yet with this videomail-client ...
