### ISSUE TITLE
Multiple email addresses

### ISSUE THREAD

**Issue by TimLewin** [binarykitchen/videomail-client#51]
I have tested videomail on Chrome (Mac)

When I was sending a video to my colleagues I have encountered difficulty in copy & paste email addresses to the "To" box as whenever I return to the videomail the "To" box shown the first email so it has made me scroll to the end but really can jump to end by pressing any key to go to the end of the box.

This is not a technical error but an improvement you can make here to make it more user friendly. For instance you can make the "To" box to enlarge for multiple emails for ease of user to put their contacts emails in.

Also here a challenging idea of installing a button "contact" next to the videomail "To" to allow user to extract their contact details from gmail or other email account. Imagine how much easier if we could be able to do that.

I hope I am clear on what I am trying to explain. Let me know if you need clarification.

**Comment by binarykitchen** [comment]
Wonderful @TimLewin, love your ideas. Will think of some ideas and fix this in the next weeks.

**Comment by binarykitchen** [comment]
@TimLewin For now, a little advice: hit the 'End' button on your keyboard to scroll to the end of an input.

**Comment by TimLewin** [comment]
Sweet. Yeah good point about the "End" button.

**Comment by binarykitchen** [comment]
@TimLewin Just have released a small update on videomail.io - the email address field is now resizable and always scrolls to the latest element. Better like that?

**Comment by TimLewin** [comment]
I have tested out the videomail for multiple email address. It's awesome, as its much easier to input the emails now. Cheers

**Comment by binarykitchen** [comment]
Great, thanks for your feedback too!
