### ISSUE TITLE
Make it work on Android's Chrome

### ISSUE THREAD

**Issue by binarykitchen** [binarykitchen/videomail-client#65]
Reported by Caffy. It behaves weird and keeps asking for permission to access webcam.

**Comment by binarykitchen** [comment]
I debugged with my Android and found this warning:

```
Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.
collectLogger.js:25 UserMedia: onLoadedMetaData()
```

**Comment by binarykitchen** [comment]
fixed!

**Comment by arefm** [comment]
@binarykitchen I have this problem. would please help me about the solution that you found ?

**Comment by binarykitchen** [comment]
it is complicated. look at the code from https://github.com/binarykitchen/videomail-client/blob/master/src/wrappers/visuals/userMedia.js#L63 onwards

in short: wrap as much as possible in try {} catch blocks and debug events, see https://github.com/binarykitchen/videomail-client/blob/master/src/wrappers/visuals/userMedia.js#L192

then, once you know more, you can improve the event handling for mobiles. that's where i found this issue, see https://github.com/binarykitchen/videomail-client/blob/master/src/wrappers/visuals/userMedia.js#L123

meta data must be loaded first before you can play a video on mobiles!
