### ISSUE TITLE
Failed to execute 'createMediaStreamSource' on 'AudioContext': MediaStream has no audio track

### ISSUE THREAD

**Issue by binarykitchen** [binarykitchen/videomail-client#72]
```
onerror: "Uncaught InvalidStateError: Failed to execute 'createMediaStreamSource' on 'AudioContext': MediaStream has no audio track"

occured at https://videomail.io/

caused by useragent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36

https://videomail.io/js/main-027c66815f.min.js:23:7134
```

**Comment by cosysun** [comment]
i meet the same problem, can you tell how do you fix it,thank you

**Comment by binarykitchen** [comment]
activate it with audio at the getusermedia api

**Comment by mizuiren** [comment]
![Koala](https://user-images.githubusercontent.com/16829552/137676876-5d1d7c70-7387-461b-9dc9-6df2a169f7e0.jpg)

**Comment by esraaabdelmonem1994** [comment]
Any update on this issue I get audio tracks from getting receivers then used  'createMediaStreamSource' but get the following error
InvalidStateError: Media stream has no audio tracks createMediaStreamSource

**Comment by binarykitchen** [comment]
@esraaabdelmonem1994 Does this problem happen in this videomail-client project or in a different project (yours)?

**Comment by esraaabdelmonem1994** [comment]
> @esraaabdelmonem1994 Does this problem happen in this videomail-client project or in a different project (yours)?

This problem happens in a different scenario when I'm trying to merge audio tracks into one track

**Comment by binarykitchen** [comment]
So, it's a different project / repository, and you are asking for advice? 

Maybe I can help if you point me to the repository and the relevant code.

**Comment by esraaabdelmonem1994** [comment]
@binarykitchen  I added a post in StackOverflow and added the code there 
can you check this, please
https://stackoverflow.com/questions/74547663/ios-error-media-stream-has-no-audio-tracks-createmediastreamsource

**Comment by binarykitchen** [comment]
@esraaabdelmonem1994 afraid your code example is too bloated and needs narrowing down to one simple use case. Hard to help.

Recommend to look at this repo for inspiration:
https://github.com/microphone-stream/microphone-stream

PS: videomail-client uses one mono audio stream, it doesn't merge multiple audio tracks so, hard to tell from here. Furthermore, I had the problem in 2016 (see original comment of this ticket). I solved it somehow, but cannot remember what the solution was. That was six years ago ...
